// Generates supabase/seed.sql FROM the typed seed so the offline data layer and
// the future Supabase database share one source of truth.
//
// Run: npm run db:seed-sql
// (Node strips the TS types natively; offRoad.ts imports only `import type`.)

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { offRoadCatalog } from "../src/data/seed/offRoad.ts";
import { CATEGORY_ORDER } from "../src/domain/types.ts";
import type { Component } from "../src/domain/types.ts";

const q = (v: string | null | undefined): string =>
  v == null ? "null" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined): string => (v == null ? "null" : String(v));
const b = (v: boolean): string => (v ? "true" : "false");
const frameArr = (v: Component["compatibleFrameTypes"]): string =>
  v == null ? "null" : `'{${v.join(",")}}'`;

const lines: string[] = [
  "-- GENERATED by scripts/generate-seed-sql.mts — do not edit by hand.",
  "-- Source of truth: src/data/seed/offRoad.ts",
  "",
  "begin;",
  "",
];

const { line, components, extras, incompatibilities, presets } = offRoadCatalog;

lines.push("-- Product line");
lines.push(
  `insert into product_line (id, slug, name, description, base_price_cents, currency) values (${q(line.id)}, ${q(line.slug)}, ${q(line.name)}, ${q(line.description)}, ${n(line.basePriceCents)}, ${q(line.currency)});`,
  "",
);

lines.push("-- Components");
// Emit in guided-category order, then sort_order, for readable diffs.
const orderedComponents = [...components].sort(
  (a, b) =>
    CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category) ||
    a.sortOrder - b.sortOrder,
);
for (const c of orderedComponents) {
  lines.push(
    `insert into components (id, line_id, category, name, description, price_delta_cents, frame_type, compatible_frame_types, motor_type, voltage, swatch, layer_asset, closeup_asset, is_default, sort_order) values (` +
      `${q(c.id)}, ${q(c.lineId)}, ${q(c.category)}, ${q(c.name)}, ${q(c.description)}, ${n(c.priceDeltaCents)}, ${q(c.frameType)}, ${frameArr(c.compatibleFrameTypes)}, ${q(c.motorType)}, ${n(c.voltage)}, ${q(c.swatch)}, ${q(c.layerAsset)}, ${q(c.closeupAsset)}, ${b(c.isDefault)}, ${n(c.sortOrder)});`,
  );
}
lines.push("");

lines.push("-- Extras");
for (const e of [...extras].sort((a, b) => a.sortOrder - b.sortOrder)) {
  lines.push(
    `insert into extras (id, line_id, name, description, price_delta_cents, compatible_frame_types, note, enables_street_legal, sort_order) values (` +
      `${q(e.id)}, ${q(e.lineId)}, ${q(e.name)}, ${q(e.description)}, ${n(e.priceDeltaCents)}, ${frameArr(e.compatibleFrameTypes)}, ${q(e.note)}, ${b(e.enablesStreetLegal ?? false)}, ${n(e.sortOrder)});`,
  );
}
lines.push("");

lines.push("-- Explicit incompatibilities");
for (const rule of incompatibilities) {
  lines.push(
    `insert into compatibility (component_a, component_b, reason) values (${q(rule.a)}, ${q(rule.b)}, ${q(rule.reason)});`,
  );
}
lines.push("");

lines.push("-- Presets and their components");
for (const p of presets) {
  lines.push(
    `insert into presets (id, line_id, tier, name, tagline, hero_asset, sort_order) values (${q(p.id)}, ${q(p.lineId)}, ${n(p.tier)}, ${q(p.name)}, ${q(p.tagline)}, ${q(p.heroAsset)}, ${n(p.sortOrder)});`,
  );
  for (const cid of p.componentIds) {
    lines.push(
      `insert into preset_components (preset_id, component_id) values (${q(p.id)}, ${q(cid)});`,
    );
  }
  for (const eid of p.extraIds ?? []) {
    lines.push(`insert into preset_extras (preset_id, extra_id) values (${q(p.id)}, ${q(eid)});`);
  }
  lines.push("");
}

lines.push("commit;");
lines.push("");

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote ${outPath} (${orderedComponents.length} components, ${presets.length} presets).`);
